name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8, 12]
    steps:
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Set up JDK $
      uses: actions/setup-java@v1
      with:
        java-version: $
    - name: Make Gradle Wrapper executable
      if: contains(matrix.os, 'win') == false
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
